### ISSUE TITLE
runtime org.gnome.Platform branch 45 is end-of-life

### ISSUE THREAD

**Issue by tobiasmicheler** [flathub/io.github.bytezz.IPLookup#16]
Info: runtime org.gnome.Platform branch 45 is end-of-life, with reason:
   The GNOME 45 runtime is no longer supported as of September 18, 2024. Please ask your application developer to migrate to a supported platform.
Info: applications using this runtime:
   io.github.bytezz.IPLookup

**Comment by Bytezz** [comment]
Hi @tobiasmicheler, I'm trying to merge [last branch](https://github.com/Bytezz/IPLookup-gtk/tree/reveal-animation) and then I'll update the flathub repo.  
Thanks for the reminder :+1:
